repos:
  - fedora
packages:
  - "@Fedora Cloud Server"
  - chrony
  - efibootmgr
  - kernel
  - langpacks-en
  - nss-altfiles
  - ostree
  - qemu-guest-agent
  - rpm-ostree
  - selinux-policy-targeted
  - spice-vdagent
  - xen-libs
  - fedora-repos-ostree
packages-x86_64:
  - grub2-efi-ia32
  - grub2-efi-x64
  - grub2-pc
  - grub2-tools
  - shim-ia32
  - shim-x64
packages-exclude:
  - dracut-config-rescue
  - Package
