ref: fedora/x86_64/osbuild-demo
repos:
  - fedora
packages:
  - fedora-release-iot
  - glibc
  - glibc-minimal-langpack
  - nss-altfiles
  - sssd-client
  - libsss_sudo
  - shadow-utils
  - kernel
  - dracut-config-generic
  - dracut-network
  - rpm-ostree
  - polkit
  - lvm2
  - cryptsetup
  - pinentry
  - keyutils
  - cracklib-dicts
  - e2fsprogs
  - xfsprogs
  - dosfstools
  - gnupg2
  - basesystem
  - python3
  - bash
  - xz
  - gzip
  - zram
  - coreutils
  - which
  - curl
  - firewalld
  - iptables
  - NetworkManager
  - NetworkManager-wifi
  - NetworkManager-wwan
  - wpa_supplicant
  - iwd
  - tpm2-pkcs11
  - dnsmasq
  - traceroute
  - hostname
  - iproute
  - iputils
  - openssh-clients
  - openssh-server
  - passwd
  - policycoreutils
  - procps-ng
  - rootfiles
  - rpm
  - selinux-policy-targeted
  - setup
  - shadow-utils
  - sudo
  - systemd
  - util-linux
  - vim-minimal
  - less
  - tar
  - fwupd
  - usbguard
  - greenboot
  - greenboot-grub2
  - greenboot-rpm-ostree-grub2
  - greenboot-reboot
  - greenboot-status
  - ignition
  - zezere-ignition
  - rsync
  - attr
  - ima-evm-utils
  - bash-completion
  - tmux
  - screen
  - policycoreutils-python-utils
  - setools-console
  - audit
  - rng-tools
  - chrony
  - bluez
  - bluez-libs
  - bluez-mesh
  - wpan-tools
  - kernel-tools
  - libgpiod-utils
  - podman
  - podman-plugins
  - container-selinux
  - skopeo
  - criu
  - slirp4netns
  - fuse-overlayfs
  - clevis
  - clevis-dracut
  - clevis-luks
  - clevis-pin-tpm2
  - parsec
  - dbus-parsec
packages-x86_64:
  - grub2
  - grub2-efi-x64
  - efibootmgr
  - shim-x64
  - microcode_ctl
  - iwl1000-firmware
  - iwl100-firmware
  - iwl105-firmware
  - iwl135-firmware
  - iwl2000-firmware
  - iwl2030-firmware
  - iwl3160-firmware
  - iwl5000-firmware
  - iwl5150-firmware
  - iwl6000-firmware
  - iwl6050-firmware
  - iwl7260-firmware
packages-exclude:
  - dracut-config-rescue
  - PackageKit
units:
  - NetworkManager.service
  - firewalld.service
  - rngd.service
  - sshd.service
  - zezere_ignition.timer
  - zezere_ignition_banner.service
  - greenboot-grub2-set-counter
  - greenboot-grub2-set-success
  - greenboot-healthcheck
  - greenboot-rpm-ostree-grub2-check-fallback
  - greenboot-status
  - greenboot-task-runner
  - redboot-auto-reboot
  - redboot-task-runner
  - parsec
  - dbus-parsec
etc-group-members:
  - wheel
  - docker
